include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - dart_code_metrics
  exclude:
    - spec_suite/**
    - test/spec_suite/**
    - lib/spec_suite/**
    - "**/__generated__/**"
  language:
    strict-raw-types: true
  errors:
    public_member_api_docs: ignore
    lines_longer_than_80_chars: ignore
    avoid_redundant_argument_values: ignore
    cascade_invocations: ignore
    unnecessary_brace_in_string_interps: ignore
    avoid_positional_boolean_parameters: ignore
    no_leading_underscores_for_local_identifiers: ignore
    one_member_abstracts: ignore
    avoid_dynamic_calls: ignore
    comment_references: ignore
linter:
  rules:
    - prefer_final_locals
    - unawaited_futures
    - avoid_print

dcm:
  rules:
    # Show potential errors
    - avoid-cascade-after-if-null
    - avoid-collection-methods-with-unrelated-types
    - avoid-duplicate-exports
    - avoid-dynamic
    - avoid-passing-async-when-sync-expected
    - avoid-throw-in-catch-block
    - avoid-unused-parameters
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - no-empty-block
    - no-equal-then-else
    - prefer-correct-test-file-name
    - prefer-match-file-name
    - avoid-self-assignment
    - avoid-self-compare
    - prefer-iterable-of
    - avoid-missed-calls
    - avoid-generics-shadowing
    - avoid-unnecessary-conditionals
    - avoid-double-slash-imports
    - avoid-duplicate-mixins
    - always-remove-listener
    - avoid-unnecessary-setstate
    - check-for-equals-in-render-object-setters
    - consistent-update-render-object
    - use-setstate-synchronously
    - avoid-incomplete-copy-with
    - avoid-missing-image-alt
    - avoid-passing-self-as-argument
    - avoid-duplicate-test-assertions
    - avoid-nullable-tostring
    - avoid-empty-spread
    - avoid-casting-to-extension-type
    - avoid-conditions-with-boolean-literals
    - avoid-incorrect-image-opacity
    - avoid-misused-set-literals
    - avoid-assignments-as-conditions
    - avoid-commented-out-code
    # Enable with the next release
    # - avoid-mounted-in-setstate
    # - prefer-specifying-future-value-type
    # - avoid-default-tostring
    # - avoid-stream-tostring
    # - avoid-unreachable-for-loop
    # - avoid-suspicious-global-reference
    # - avoid-unnecessary-local-variable
    # - avoid-unnecessary-late-fields
    # - avoid-unnecessary-nullable-parameters
    # - avoid-never-passed-parameters
    # - avoid-wildcard-cases-with-sealed-classes
    # - avoid-unremovable-callbacks-in-listeners
    # - avoid-constant-switches
    # - avoid-constant-conditions
    # - avoid-unused-local-variable
    # - match-base-class-default-value
    # - avoid-unassigned-fields
    # - avoid-always-null-parameters
    # - avoid-nested-shorthands

    # Code simplification
    - avoid-redundant-async
    - avoid-nested-records
    - avoid-explicit-pattern-field-name
    - avoid-unnecessary-stateful-widgets
    # Enable with the next release
    # - prefer-null-aware-elements
    # - avoid-unnecessary-null-aware-elements
    # - avoid-unnecessary-statements
    # - avoid-unnecessary-length-check
    # - prefer-shorthands-with-enums
    # - prefer-shorthands-with-static-fields
    # - prefer-returning-shorthands
    # - prefer-shorthands-with-constructors

    # Style
    - prefer-single-widget-per-file