include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - spec_suite/**
    - test/spec_suite/**
    - lib/spec_suite/**
    - "**/__generated__/**"
  language:
    strict-raw-types: true
linter:
  rules:
    - prefer_final_locals
    - unawaited_futures
    - avoid_print
